### PR TITLE
merge request: 81 upgrade webpack

### LINKED ISSUE #81: Upgrade webpack
I'm gonna take a shot at this one in a fork, unless you want to, @RyanCCollins :)

One question: are there any packages known to be not-in-use? Just thinking of simplifying before ironing out dependencies and compatibilities.

Goal is to end up with 2.2.1 or better.
Migration path: https://webpack.js.org/guides/migrating/#module-preloaders-and-module-postloaders-was-removed

### PR DESCRIPTION
**Pull request by monte-hayward**
fixes #81 upgrade webpack

### CODE REVIEW

**Comment by RyanCCollins** [comment]
Awesome, thanks for this!  It's really appreciated.  I will pull and check it out and merge it soon.

**Comment by RyanCCollins** [comment]
Hey @monte-hayward, I've ran this locally and it looks like the css modules aren't making it into the production bundle.  Not sure why.  Any ideas?

**Comment by RyanCCollins** [comment]
I added extract text plugin to modules and it appears to be working, so I am going to merge this.  Thanks again for your hard work figuring it out!

**Comment by monte-hayward** [comment]
thanks for tracking down the css-modules thing!

**Pull request merged**
